# Generated by Django 2.1.2 on 2018-11-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0002_orange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tubelight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('voltage', models.DecimalField(decimal_places=2, max_digits=13)),
                ('types', models.TextField()),
                ('summary', models.TextField()),
                ('featured', models.BooleanField(default=True)),
            ],
        ),
    ]
